name: Test

on:
  push:
    branches:
      - "dev/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ["3.3"]
        redmine: ["master", "5.1-stable"]

    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            bzr git mercurial subversion cvs \
            ghostscript \
            gsfonts \
            imagemagick libmagick++-dev

          sudo sed -ri 's/(rights)="none" (pattern="PDF")/\1="read" \2/' /etc/ImageMagick-6/policy.xml;

      - uses: browser-actions/setup-chrome@v1
      - run: chrome --version

      - uses: actions/checkout@v4

      - run: |
          cat <<EOS > config/database.yml
          development:
            adapter: sqlite3
            database: db/development.sqlite3
          test:
            adapter: sqlite3
            database: db/test.sqlite3
          EOS

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - run: bin/rails db:migrate
        env:
          RAILS_ENV: test

      - run: bin/rails test
      - run: bin/rails test:system
        env:
          GOOGLE_CHROME_OPTS_ARGS: "headless,disable-gpu,no-sandbox,disable-dev-shm-usage"
